static char * paicolor[] = {
"A	c #999999",
"B	c #000000",
"C	c #cd8500",
"D	c #ff3030",
"E      c #228b22",
"F      c #8470ff",
"G	c #22228b",
"H	c darkseagreen",
};


/* "37 54" */
static char * paidata[] = {
/* man1_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                        AA           ",
"                    AABBBBBA         ",
"                AABBBBBBBBBBBA       ",
"           AAABBBBBBBBBBBBBBBA       ",
"     ABBBBBBBBBAA         AAA        ",
"      BBBBBBBA                       ",
"       BBBBA                         ",
"        AA                           ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCDD           ",
"            D  DD  CDDDDDDDC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man2_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                  AA                 ",
"                ABBBBA               ",
"              AABBBBBBA              ",
"         ABBBBBBBBBBAA               ",
"          BBBBBBAA                   ",
"           ABAA                      ",
"                                     ",
"                                     ",
"                        AA           ",
"                    AABBBBBA         ",
"                 AABBBBBBBBBBA       ",
"            AAABBBBBBBBBBBBBBA       ",
"     ABBBBBBBBBAAA        AAA        ",
"      BBBBBBBA                       ",
"       BBBBA                         ",
"        AA                           ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDCCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD   DDDD       ",
"        CDD    DDDD CDC  CDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man3_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                  ABBA               ",
"               AABBBBBB              ",
"         ABAABBBBBBAAA               ",
"          ABBBBBAA                   ",
"           ABAA                      ",
"                                     ",
"                ABBBA                ",
"            BBBBBBBBB                ",
"             ABBAA                   ",
"                                     ",
"                      AABBBA         ",
"                   AABBBBBBBBA       ",
"               AAABBBBBBBBBBBBA      ",
"     AAAAAAAABBBBBBAAA AAABBBA       ",
"      BBBBBBBBBBAA                   ",
"       BBBBBBAA                      ",
"        ABAA                         ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDD               ",
"          C DDDDD  DDD               ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD   DDDD       ",
"        CDD    DDDD CDC  CDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man4_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 AAABBBBBA           ",
"             AABBBBBBBBBBBBA         ",
"          AABBBAA BA    BBBBB        ",
"      BBBBBBAA    BBA   BBBBB        ",
"      BBB   BB    BBA   BBBBA        ",
"      ABBA  BBA   BB   ABBBB         ",
"       BBB   BB   BB   BBBBA         ",
"       ABBA  AB   B AABBBBA          ",
"        ABB   BABBBBBBBBBB           ",
"         BBBABBAA     BBB            ",
"         ABBBA                       ",
"          BB                         ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man5_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                    AAA              ",
"              A    ABBBB             ",
"           A   BBBBBBBBA             ",
"           BA   BABAA                ",
"           BBA     BA                ",
"          BBB      B                 ",
"         ABB      BABBA              ",
"         BB    AABBBBBBA             ",
"        BAB ABBBBBA  BBBA            ",
"       BA BB ABBABA  BBBA            ",
"      BA  BB  AA B  ABBA             ",
"          BA    BA  ABB              ",
"         BBA    B   BBA              ",
"        ABB BBBBBBBBBBBBBBBBBBBA     ",
"        BBA ABBBBAA     ABBBBBA      ",
"        ABA  ABA          ABAA       ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man6_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"             ABA                     ",
"              BBB                    ",
"              ABBB   AAAA            ",
"               BBB  ABBBBBA          ",
"               BA ABBBBBBBBA         ",
"               BBBBBBBBBBBA          ",
"      ABBBAABBBBBAAA                 ",
"       ABBBBBBAAA                    ",
"        ABBBAA                       ",
"          AA                         ",
"                  ABBAAA             ",
"           AA       ABBAAA           ",
"           BBAA      ABBBAA          ",
"           BBBA       ABBBA          ",
"           BBA      ABABBBB          ",
"          ABA         BBBBA          ",
"         ABA           AAAA          ",
"        AAA                          ",
"       A                             ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man7_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"            AAA                      ",
"            BBBA                     ",
"            BBBBA                    ",
"            ABBBB                    ",
"            ABBBB                    ",
"             BBBA     AA             ",
"             BBBA   ABBBBA           ",
"             BBA   ABBBBBA           ",
"             BBA  BBBBBAA            ",
"             BBAABBBAA               ",
"             BBBBAAA                 ",
"            ABBBA                    ",
"        AAABBBBA                     ",
"         BBBABBA                     ",
"             ABBAAABAA               ",
"              ABBBBBBBA              ",
"               ABBBBBBA              ",
"                AABBAA               ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man8_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"              A                      ",
"              AA                     ",
"              ABA                    ",
"               BBA                   ",
"               ABBA                  ",
"                ABBA                 ",
"           A    ABBBA                ",
"          AB     ABBBA               ",
"         ABBA     ABBBA              ",
"         ABBBA    ABBBBA             ",
"        ABBBA      ABBBBBAA          ",
"        ABBA        ABBBBBBBAA       ",
"       ABBA         ABBBBBBBBBBA     ",
"      ABAA           ABBBBBAAA       ",
"      BA              AAAA           ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* man9_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"              BA                     ",
"              BBA                    ",
"              BBBA                   ",
"              ABB                    ",
"              ABA BB                 ",
"              ABABBBB                ",
"              BBBABBBB               ",
"           AABBB  ABBA               ",
"          BBB BB  ABA                ",
"           B  BA  ABA     A          ",
"             ABA  BAA     B          ",
"             BAA  BA      BA         ",
"            ABA   BA      BA         ",
"            BAA   BA     ABBA        ",
"           ABA    BA     ABBBA       ",
"          ABA     ABA  AABBBBB       ",
"         ABA       ABBBBBBBBAA       ",
"        AA           AAAAAA          ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCC          ",
"                                     ",
"                                     ",
"                                     ",
/* pin1_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"               FFFFFFF               ",
"            FGGGGGGGGGGGF            ",
"          FGGGGFFFFFFFGGGGF          ",
"         FGGG           FGGF         ",
"        GGG   FGGGGGGGF   GGG        ",
"       GGF  GGF       FGG  FGG       ",
"      FGF  GGG GGGGGGG GGG  FGF      ",
"     FGG  G    GGGGGGG    G  GGF     ",
"     GG  G  G  GGGGGGG  G  G  GG     ",
"    FGF FF GGGG       GGGG FF FGF    ",
"    GG  G  GGF  CCCCC  FGG  G  GG    ",
"    GG FF GGG CC     CC GGG FF GG    ",
"   FGF F  GG  CC CCC CC  GG  F FGF   ",
"   FGF G GGG C  CCCCC  C GGG G FGF   ",
"   FGF G  GG C CC C CC C GG  G FGF   ",
"   FGF GG  G C CCCCCCC C G  GG FGF   ",
"   FGF G  GG C  C C C  C GG  G FGF   ",
"   FGF G GGG CC CCCCC CC GGG G FGF   ",
"   FGF F  GG  C  C C  C  GG  F FGF   ",
"    GG FF GGG CC  C  CC GGG FF GG    ",
"    GG  G  GGF  CCCCC  FGG  G  GG    ",
"    FGF FF GGGG       GGGG FF FGF    ",
"     GG  G  G  GGGGGGG  G  G  GG     ",
"     FGG  G    GGGGGGG    G  GGF     ",
"      FGF  GGG GGGGGGG GGG  FGF      ",
"       GGF  GGF       FGG  FGG       ",
"        GGG   FGGGGGGGF   GGG        ",
"         FGGF           FGGF         ",
"          FGGGGFFFFFFFGGGGF          ",
"            FGGGGGGGGGGGF            ",
"               FFFFFFF               ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* pin2_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                FFFFF                ",
"              FFGGGGGFF              ",
"             FGG     GGF             ",
"            FG   GGG   GF            ",
"           FG  GGF FGG  GF           ",
"           FG GFG F GFG GF           ",
"          FG  G G G G G  GF          ",
"          FG G F G G F G GF          ",
"          FG G  G G G  G GF          ",
"          FG GFG G G GFG GF          ",
"          FG  GFF G FFG  GF          ",
"           FG G   G   G GF           ",
"           FG  GGFGFGG  GF           ",
"            FG   GGG   GF            ",
"             FGG     GGF             ",
"              FFGGGGGFF              ",
"                FFFFF                ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                FFFFF                ",
"              FFGGGGGFF              ",
"             FGG     GGF             ",
"            FG   GGG   GF            ",
"           FG  GGF FGG  GF           ",
"           FG GFG F GFG GF           ",
"          FG  G G G G G  GF          ",
"          FG G F G G F G GF          ",
"          FG G  G G G  G GF          ",
"          FG GFG G G GFG GF          ",
"          FG  GFF G FFG  GF          ",
"           FG G   G   G GF           ",
"           FG  GGFGFGG  GF           ",
"            FG   GGG   GF            ",
"             FGG     GGF             ",
"              FFGGGGGFF              ",
"                FFFFF                ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* pin3_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"       FFFFF                         ",
"     FFGGGGGFF                       ",
"    FGG     GGF                      ",
"   FG  GGGGG  GF                     ",
"   FG GGF FGG GF                     ",
"  FG GF GGG FG GF                    ",
"  FG G  G G  G GF                    ",
"  FG GFG G GFG GF                    ",
"  FG GG G G GG GF                    ",
"  FG GF  G  FG GF                    ",
"   FG G FGF G GF                     ",
"   FG  GGGGG  GF                     ",
"    FGG     GGF                      ",
"     FFGGGGGFF                       ",
"       FFFFF                         ",
"                                     ",
"                CCCCC                ",
"              CCCCCCCCC              ",
"             CCC     CCC             ",
"            CC  CCCCC  CC            ",
"            CC CCC CCC CC            ",
"           CC CC CCC CC CC           ",
"           CC C  C C  C CC           ",
"           CC CCC C CCC CC           ",
"           CC CC C C CC CC           ",
"           CC CC  C  CC CC           ",
"            CC C CCC C CC            ",
"            CC  CCCCC  CC            ",
"             CCC     CCC             ",
"              CCCCCCCCC              ",
"                CCCCC                ",
"                                     ",
"                         FFFFF       ",
"                       FFGGGGGFF     ",
"                      FGG     GGF    ",
"                     FG  GGGGG  GF   ",
"                     FG GGF FGG GF   ",
"                    FG GF GGG FG GF  ",
"                    FG G  G G  G GF  ",
"                    FG GFG G GFG GF  ",
"                    FG GG G G GG GF  ",
"                    FG GF  G  FG GF  ",
"                     FG G FGF G GF   ",
"                     FG  GGGGG  GF   ",
"                      FGG     GGF    ",
"                       FFGGGGGFF     ",
"                         FFFFF       ",
"                                     ",
"                                     ",
"                                     ",
/* pin4_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"       FGGGF             FGGGF       ",
"     FGF   FGF         FGF   FGF     ",
"    FG  GGG  GF       FG  GGG  GF    ",
"    G FGF FGF G       G FGF FGF G    ",
"   FF G GGG G FF     FF G GGG G FF   ",
"   G G  G G  G G     G G  G G  G G   ",
"   G GFG G GFG G     G GFG G GFG G   ",
"   G GG G G GG G     G GG G G GG G   ",
"   FF G  G  G FF     FF G  G  G FF   ",
"    G FGFGFGF G       G FGFGFGF G    ",
"    FG  GGG  GF       FG  GGG  GF    ",
"     FGF   FGF         FGF   FGF     ",
"       FGGGF             FGGGF       ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"       FGGGF             FGGGF       ",
"     FGF   FGF         FGF   FGF     ",
"    FG  GGG  GF       FG  GGG  GF    ",
"    G FGF FGF G       G FGF FGF G    ",
"   FF G GGG G FF     FF G GGG G FF   ",
"   G G  G G  G G     G G  G G  G G   ",
"   G GFG G GFG G     G GFG G GFG G   ",
"   G GG G G GG G     G GG G G GG G   ",
"   FF G  G  G FF     FF G  G  G FF   ",
"    G FGFGFGF G       G FGFGFGF G    ",
"    FG  GGG  GF       FG  GGG  GF    ",
"     FGF   FGF         FGF   FGF     ",
"       FGGGF             FGGGF       ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* pin5_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"       FGGGF             FGGGF       ",
"     FGF   FGF         FGF   FGF     ",
"    FG  GGG  GF       FG  GGG  GF    ",
"    G FGF FGF G       G FGF FGF G    ",
"   FF G GGG G FF     FF G GGG G FF   ",
"   G G  G G  G G     G G  G G  G G   ",
"   G GFG G GFG G     G GFG G GFG G   ",
"   G GG G G GG G     G GG G G GG G   ",
"   FF G  G  G FF     FF G  G  G FF   ",
"    G FGFGFGF G       G FGFGFGF G    ",
"    FG  GGG  GF       FG  GGG  GF    ",
"     FGF   FGF         FGF   FGF     ",
"       FGGGF             FGGGF       ",
"                                     ",
"                                     ",
"                CCCCC                ",
"              CCC   CCC              ",
"             CC  CCC  CC             ",
"             C CCC CCC C             ",
"            CC C CCC C CC            ",
"            C C  C C  C C            ",
"            C CCC C CCC C            ",
"            C CC C C CC C            ",
"            CC C  C  C CC            ",
"             C CCCCCCC C             ",
"             CC  CCC  CC             ",
"              CCC   CCC              ",
"                CCCCC                ",
"                                     ",
"                                     ",
"       FGGGF             FGGGF       ",
"     FGF   FGF         FGF   FGF     ",
"    FG  GGG  GF       FG  GGG  GF    ",
"    G FGF FGF G       G FGF FGF G    ",
"   FF G GGG G FF     FF G GGG G FF   ",
"   G G  G G  G G     G G  G G  G G   ",
"   G GFG G GFG G     G GFG G GFG G   ",
"   G GG G G GG G     G GG G G GG G   ",
"   FF G  G  G FF     FF G  G  G FF   ",
"    G FGFGFGF G       G FGFGFGF G    ",
"    FG  GGG  GF       FG  GGG  GF    ",
"     FGF   FGF         FGF   FGF     ",
"       FGGGF             FGGGF       ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* pin6_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"         FGGGF         FGGGF         ",
"       FGF   FGF     FGF   FGF       ",
"      FG  GGG  GF   FG  GGG  GF      ",
"      G FGF FGF G   G FGF FGF G      ",
"     FF G GGG G FF FF G GGG G FF     ",
"     G G  G G  G G G G  G G  G G     ",
"     G GFG G GFG G G GFG G GFG G     ",
"     G GG G G GG G G GG G G GG G     ",
"     FF G  G  G FF FF G  G  G FF     ",
"      G FGFGFGF G   G FGFGFGF G      ",
"      FG  GGG  GF   FG  GGG  GF      ",
"       FGF   FGF     FGF   FGF       ",
"         FGGGF         FGGGF         ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"         CCCCC         CCCCC         ",
"       CCC   CCC     CCC   CCC       ",
"      CC  CCC  CC   CC  CCC  CC      ",
"      C CCC CCC C   C CCC CCC C      ",
"     CC C CCC C CC CC C CCC C CC     ",
"     C C  C C  C C C C  C C  C C     ",
"     C CCC C CCC C C CCC C CCC C     ",
"     C CC C C CC C C CC C C CC C     ",
"     CC C  C  C CC CC C  C  C CC     ",
"      C CCCCCCC C   C CCCCCCC C      ",
"      CC  CCC  CC   CC  CCC  CC      ",
"       CCC   CCC     CCC   CCC       ",
"         CCCCC         CCCCC         ",
"                                     ",
"         CCCCC         CCCCC         ",
"       CCC   CCC     CCC   CCC       ",
"      CC  CCC  CC   CC  CCC  CC      ",
"      C CCC CCC C   C CCC CCC C      ",
"     CC C CCC C CC CC C CCC C CC     ",
"     C C  C C  C C C C  C C  C C     ",
"     C CCC C CCC C C CCC C CCC C     ",
"     C CC C C CC C C CC C C CC C     ",
"     CC C  C  C CC CC C  C  C CC     ",
"      C CCCCCCC C   C CCCCCCC C      ",
"      CC  CCC  CC   CC  CCC  CC      ",
"       CCC   CCC     CCC   CCC       ",
"         CCCCC         CCCCC         ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* pin7_xpm[] */
"                                     ",
"    FGGGF                            ",
"  FGF   FGF                          ",
" FG  GGG  GF                         ",
" G FGF FGF G                         ",
"FF G GGG G FF                        ",
"G G  G G  G G                        ",
"G GFG G GFG G   FGGGF                ",
"G GG G G GG G FGF   FGF              ",
"FF G  G  G FFFG  GGG  GF             ",
" G FGFGFGF G G FGF FGF G             ",
" FG  GGG  GFFF G GGG G FF            ",
"  FGF   FGF G G  G G  G G            ",
"    FGGGF   G GFG G GFG G   FGGGF    ",
"            G GG G G GG G FGF   FGF  ",
"            FF G  G  G FFFG  GGG  GF ",
"             G FGFGFGF G G FGF FGF G ",
"             FG  GGG  GFFF G GGG G FF",
"              FGF   FGF G G  G G  G G",
"                FGGGF   G GFG G GFG G",
"                        G GG G G GG G",
"                        FF G  G  G FF",
"                         G FGFGFGF G ",
"                         FG  GGG  GF ",
"                          FGF   FGF  ",
"                            FGGGF    ",
"         CCCCC         CCCCC         ",
"       CCC   CCC     CCC   CCC       ",
"      CC  CCC  CC   CC  CCC  CC      ",
"      C CCC CCC C   C CCC CCC C      ",
"     CC C CCC C CC CC C CCC C CC     ",
"     C C  C C  C C C C  C C  C C     ",
"     C CCC C CCC C C CCC C CCC C     ",
"     C CC C C CC C C CC C C CC C     ",
"     CC C  C  C CC CC C  C  C CC     ",
"      C CCCCCCC C   C CCCCCCC C      ",
"      CC  CCC  CC   CC  CCC  CC      ",
"       CCC   CCC     CCC   CCC       ",
"         CCCCC         CCCCC         ",
"                                     ",
"         CCCCC         CCCCC         ",
"       CCC   CCC     CCC   CCC       ",
"      CC  CCC  CC   CC  CCC  CC      ",
"      C CCC CCC C   C CCC CCC C      ",
"     CC C CCC C CC CC C CCC C CC     ",
"     C C  C C  C C C C  C C  C C     ",
"     C CCC C CCC C C CCC C CCC C     ",
"     C CC C C CC C C CC C C CC C     ",
"     CC C  C  C CC CC C  C  C CC     ",
"      C CCCCCCC C   C CCCCCCC C      ",
"      CC  CCC  CC   CC  CCC  CC      ",
"       CCC   CCC     CCC   CCC       ",
"         CCCCC         CCCCC         ",
"                                     ",
/* pin8_xpm[] */
"                                     ",
"         FGGGF         FGGGF         ",
"       FGF   FGF     FGF   FGF       ",
"      FG  GGG  GF   FG  GGG  GF      ",
"      G FGF FGF G   G FGF FGF G      ",
"     FF G GGG G FF FF G GGG G FF     ",
"     G G  G G  G G G G  G G  G G     ",
"     G GFG G GFG G G GFG G GFG G     ",
"     G GG G G GG G G GG G G GG G     ",
"     FF G  G  G FF FF G  G  G FF     ",
"      G FGFGFGF G   G FGFGFGF G      ",
"      FG  GGG  GF   FG  GGG  GF      ",
"       FGF   FGF     FGF   FGF       ",
"         FGGGF         FGGGF         ",
"         FGGGF         FGGGF         ",
"       FGF   FGF     FGF   FGF       ",
"      FG  GGG  GF   FG  GGG  GF      ",
"      G FGF FGF G   G FGF FGF G      ",
"     FF G GGG G FF FF G GGG G FF     ",
"     G G  G G  G G G G  G G  G G     ",
"     G GFG G GFG G G GFG G GFG G     ",
"     G GG G G GG G G GG G G GG G     ",
"     FF G  G  G FF FF G  G  G FF     ",
"      G FGFGFGF G   G FGFGFGF G      ",
"      FG  GGG  GF   FG  GGG  GF      ",
"       FGF   FGF     FGF   FGF       ",
"         FGGGF         FGGGF         ",
"         FGGGF         FGGGF         ",
"       FGF   FGF     FGF   FGF       ",
"      FG  GGG  GF   FG  GGG  GF      ",
"      G FGF FGF G   G FGF FGF G      ",
"     FF G GGG G FF FF G GGG G FF     ",
"     G G  G G  G G G G  G G  G G     ",
"     G GFG G GFG G G GFG G GFG G     ",
"     G GG G G GG G G GG G G GG G     ",
"     FF G  G  G FF FF G  G  G FF     ",
"      G FGFGFGF G   G FGFGFGF G      ",
"      FG  GGG  GF   FG  GGG  GF      ",
"       FGF   FGF     FGF   FGF       ",
"         FGGGF         FGGGF         ",
"         FGGGF         FGGGF         ",
"       FGF   FGF     FGF   FGF       ",
"      FG  GGG  GF   FG  GGG  GF      ",
"      G FGF FGF G   G FGF FGF G      ",
"     FF G GGG G FF FF G GGG G FF     ",
"     G G  G G  G G G G  G G  G G     ",
"     G GFG G GFG G G GFG G GFG G     ",
"     G GG G G GG G G GG G G GG G     ",
"     FF G  G  G FF FF G  G  G FF     ",
"      G FGFGFGF G   G FGFGFGF G      ",
"      FG  GGG  GF   FG  GGG  GF      ",
"       FGF   FGF     FGF   FGF       ",
"         FGGGF         FGGGF         ",
"                                     ",
/* pin9_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"    FGGGF       FGGGF       FGGGF    ",
"  FGF   FGF   FGF   FGF   FGF   FGF  ",
" FG  GGG  GF FG  GGG  GF FG  GGG  GF ",
" G FGF FGF G G FGF FGF G G FGF FGF G ",
"FF G GGG G FFF G GGG G FFF G GGG G FF",
"G G  G G  G G G  G G  G G G  G G  G G",
"G GFG G GFG G GFG G GFG G GFG G GFG G",
"G GG G G GG G GG G G GG G GG G G GG G",
"FF G  G  G FFF G  G  G FFF G  G  G FF",
" G FGFGFGF G G FGFGFGF G G FGFGFGF G ",
" FG  GGG  GF FG  GGG  GF FG  GGG  GF ",
"  FGF   FGF   FGF   FGF   FGF   FGF  ",
"    FGGGF       FGGGF       FGGGF    ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"    CCCCC       CCCCC       CCCCC    ",
"  CCC   CCC   CCC   CCC   CCC   CCC  ",
" CC  CCC  CC CC  CCC  CC CC  CCC  CC ",
" C CCC CCC C C CCC CCC C C CCC CCC C ",
"CC C CCC C CCC C CCC C CCC C CCC C CC",
"C C  C C  C C C  C C  C C C  C C  C C",
"C CCC C CCC C CCC C CCC C CCC C CCC C",
"C CC C C CC C CC C C CC C CC C C CC C",
"CC C  C  C CCC C  C  C CCC C  C  C CC",
" C CCCCCCC C C CCCCCCC C C CCCCCCC C ",
" CC  CCC  CC CC  CCC  CC CC  CCC  CC ",
"  CCC   CCC   CCC   CCC   CCC   CCC  ",
"    CCCCC       CCCCC       CCCCC    ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"    FGGGF       FGGGF       FGGGF    ",
"  FGF   FGF   FGF   FGF   FGF   FGF  ",
" FG  GGG  GF FG  GGG  GF FG  GGG  GF ",
" G FGF FGF G G FGF FGF G G FGF FGF G ",
"FF G GGG G FFF G GGG G FFF G GGG G FF",
"G G  G G  G G G  G G  G G G  G G  G G",
"G GFG G GFG G GFG G GFG G GFG G GFG G",
"G GG G G GG G GG G G GG G GG G G GG G",
"FF G  G  G FFF G  G  G FFF G  G  G FF",
" G FGFGFGF G G FGFGFGF G G FGFGFGF G ",
" FG  GGG  GF FG  GGG  GF FG  GGG  GF ",
"  FGF   FGF   FGF   FGF   FGF   FGF  ",
"    FGGGF       FGGGF       FGGGF    ",
"                                     ",
"                                     ",
"                                     ",
/* sou1_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"            EHEH   EHHEEHHE          ",
"            H HHH  HEHHHEEEHE        ",
"             HEHE EHHEHHHHHEEH       ",
"        E   HEHHHEHHEHEEHHHHHEH  H   ",
"       EHEE EHEHHHHHEHHHEHHEEHHHEHH  ",
"       EEHHHEHHHHHH EHHHHHHHEHHHHHE  ",
"       HHHEHEHHHHHH EHEHHEHEHHEHEHH  ",
"       HHHHH E EEHHH HHHEEEHHHHHEHH  ",
"       HHHHHHHEH EEHHEEH HHEEHHHHHE  ",
"       EHHH HEHEEHEE HHHEHHEEHHHHHE  ",
"        HHE HEHEE EE HHHEHHEEHHHHE   ",
"         HEHE EHHEEHH  HEHE  HHHHE   ",
"         HHEE EHHEEHH  HEHEEEHEHE    ",
"          EHEHEEEHHHHEEEHHHHHHHH     ",
"          C HHHEEHEHEEEEEHHHHH H     ",
"          CC HHEEHEHE  HEE H HHHE    ",
"          CC HHEEHHHE  HEHHHHEH      ",
"          CC    EEEHEHHHHHHHHE EE    ",
"          CC  HHHEEHEHHHE HH HHHH    ",
"          HHE  EEEEEEEHHEH HHHEH     ",
"         H  EEEHHEEEEHHEHHHHH EEE    ",
"         CE HE   HHHEHHHEHHH E EHHH  ",
"       CCCE EE   HHHEHEHHH H HH HHH  ",
"      CC  HHE   H  HEHHHHEEHHHEEHH   ",
"      C CC HHEHHHHHEHHHHHHHEEHHHH    ",
"     C CC  HHHEHEHH HHHHEEEHH HEH    ",
"       C  EHHEHEEHHHHHHEHHHHHHH      ",
"          EHHEHHHHEHHHHEHHH HH       ",
"  HEHH    H EHHEEHHEHHHEHHH H        ",
" HHEHEHH  H  EHHEEEHHHHEE  HH        ",
" HEH EHHEHHH  EHHHHHHHHHHEEH         ",
" EHHEEEHEHEH   EHHEHHHHHHEEH         ",
"  EHHEEHEHHHH      HHHHEEHHH         ",
"    HEEHHEEHH      EHHHEEHH          ",
"    EHHEEHHHHH    EEE    HH          ",
"     EHHEEEHHE   EHEEEE HH           ",
"      EHEHHEEEEEEEEEEEEHH            ",
"       HHEE  EEEEE  EEE              ",
"                C   C                ",
"                C   CCC              ",
"                CCC CCC              ",
"                C C C                ",
"                C   C                ",
"                CCC C CCC            ",
"              CCCCCCCCCC             ",
"             CCCC   C                ",
"                                     ",
"                                     ",
"                                     ",
/* sou2_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"              EEEEEEEE               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              HEE  EEH               ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"              HEEEEEEH               ",
"              EEE  EEE               ",
"              EEE  EEE               ",
"              HEEEEEEH               ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"              HEE  EEH               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              EEEEEEEE               ",
"                                     ",
"                                     ",
"                                     ",
"              EEEEEEEE               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              HEE  EEH               ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"              HEEEEEEH               ",
"              EEE  EEE               ",
"              EEE  EEE               ",
"              HEEEEEEH               ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"              HEE  EEH               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              EEEEEEEE               ",
"                                     ",
"                                     ",
"                                     ",
/* sou3_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"              EEEEEEEE               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              HEE  EEH               ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"              HEEEEEEH               ",
"              EEE  EEE               ",
"              EEE  EEE               ",
"              HEEEEEEH               ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"               EE  EE                ",
"              HEE  EEH               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              EEEEEEEE               ",
"                                     ",
"                                     ",
"                                     ",
"   EEEEEEEE              EEEEEEEE    ",
"  HEEE  EEEH            HEEE  EEEH   ",
"  HEEE  EEEH            HEEE  EEEH   ",
"  HEEE  EEEH            HEEE  EEEH   ",
"   HEE  EEH              HEE  EEH    ",
"    EE  EE                EE  EE     ",
"    EE  EE                EE  EE     ",
"    EE  EE                EE  EE     ",
"    EE  EE                EE  EE     ",
"   HEEEEEEH              HEEEEEEH    ",
"   EEE  EEE              EEE  EEE    ",
"   EEE  EEE              EEE  EEE    ",
"   HEEEEEEH              HEEEEEEH    ",
"    EE  EE                EE  EE     ",
"    EE  EE                EE  EE     ",
"    EE  EE                EE  EE     ",
"    EE  EE                EE  EE     ",
"   HEE  EEH              HEE  EEH    ",
"  HEEE  EEEH            HEEE  EEEH   ",
"  HEEE  EEEH            HEEE  EEEH   ",
"  HEEE  EEEH            HEEE  EEEH   ",
"   EEEEEEEE              EEEEEEEE    ",
"                                     ",
"                                     ",
"                                     ",
/* sou4_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"     EEEEEEEE           EEEEEEEE     ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"     HEE  EEH           HEE  EEH     ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"     HEEEEEEH           HEEEEEEH     ",
"     EEE  EEE           EEE  EEE     ",
"     EEE  EEE           EEE  EEE     ",
"     HEEEEEEH           HEEEEEEH     ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"     HEE  EEH           HEE  EEH     ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"     EEEEEEEE           EEEEEEEE     ",
"                                     ",
"                                     ",
"                                     ",
"     EEEEEEEE           EEEEEEEE     ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"     HEE  EEH           HEE  EEH     ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"     HEEEEEEH           HEEEEEEH     ",
"     EEE  EEE           EEE  EEE     ",
"     EEE  EEE           EEE  EEE     ",
"     HEEEEEEH           HEEEEEEH     ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"      EE  EE             EE  EE      ",
"     HEE  EEH           HEE  EEH     ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"    HEEE  EEEH         HEEE  EEEH    ",
"     EEEEEEEE           EEEEEEEE     ",
"                                     ",
"                                     ",
"                                     ",
/* sou5_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"  EEEEEEEE                EEEEEEEE   ",
" HEEE  EEEH              HEEE  EEEH  ",
" HEEE  EEEH              HEEE  EEEH  ",
" HEEE  EEEH              HEEE  EEEH  ",
"  HEE  EEH                HEE  EEH   ",
"   EE  EE                  EE  EE    ",
"   EE  EE                  EE  EE    ",
"   EE  EE                  EE  EE    ",
"   EE  EE                  EE  EE    ",
"  HEEEEEEH                HEEEEEEH   ",
"  EEE  EEE                EEE  EEE   ",
"  EEE  EEE                EEE  EEE   ",
"  HEEEEEEH                HEEEEEEH   ",
"   EE  EE     CCCCCCCC     EE  EE    ",
"   EE  EE    CCCC  CCCC    EE  EE    ",
"   EE  EE    CCCC  CCCC    EE  EE    ",
"   EE  EE    CCCC  CCCC    EE  EE    ",
"  HEE  EEH    CCC  CCC    HEE  EEH   ",
" HEEE  EEEH    CC  CC    HEEE  EEEH  ",
" HEEE  EEEH    CC  CC    HEEE  EEEH  ",
" HEEE  EEEH    CC  CC    HEEE  EEEH  ",
"  EEEEEEEE     CC  CC     EEEEEEEE   ",
"              CCCCCCCC               ",
"              CCC  CCC               ",
"              CCC  CCC               ",
"  EEEEEEEE    CCCCCCCC    EEEEEEEE   ",
" HEEE  EEEH    CC  CC    HEEE  EEEH  ",
" HEEE  EEEH    CC  CC    HEEE  EEEH  ",
" HEEE  EEEH    CC  CC    HEEE  EEEH  ",
"  HEE  EEH     CC  CC     HEE  EEH   ",
"   EE  EE     CCC  CCC     EE  EE    ",
"   EE  EE    CCCC  CCCC    EE  EE    ",
"   EE  EE    CCCC  CCCC    EE  EE    ",
"   EE  EE    CCCC  CCCC    EE  EE    ",
"  HEEEEEEH    CCCCCCCC    HEEEEEEH   ",
"  EEE  EEE                EEE  EEE   ",
"  EEE  EEE                EEE  EEE   ",
"  HEEEEEEH                HEEEEEEH   ",
"   EE  EE                  EE  EE    ",
"   EE  EE                  EE  EE    ",
"   EE  EE                  EE  EE    ",
"   EE  EE                  EE  EE    ",
"  HEE  EEH                HEE  EEH   ",
" HEEE  EEEH              HEEE  EEEH  ",
" HEEE  EEEH              HEEE  EEEH  ",
" HEEE  EEEH              HEEE  EEEH  ",
"  EEEEEEEE                EEEEEEEE   ",
"                                     ",
"                                     ",
"                                     ",
/* sou6_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"  EEEEEEEE    EEEEEEEE    EEEEEEEE   ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
"  HEE  EEH    HEE  EEH    HEE  EEH   ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"  HEEEEEEH    HEEEEEEH    HEEEEEEH   ",
"  EEE  EEE    EEE  EEE    EEE  EEE   ",
"  EEE  EEE    EEE  EEE    EEE  EEE   ",
"  HEEEEEEH    HEEEEEEH    HEEEEEEH   ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"  HEE  EEH    HEE  EEH    HEE  EEH   ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
"  EEEEEEEE    EEEEEEEE    EEEEEEEE   ",
"                                     ",
"                                     ",
"                                     ",
"  EEEEEEEE    EEEEEEEE    EEEEEEEE   ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
"  HEE  EEH    HEE  EEH    HEE  EEH   ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"  HEEEEEEH    HEEEEEEH    HEEEEEEH   ",
"  EEE  EEE    EEE  EEE    EEE  EEE   ",
"  EEE  EEE    EEE  EEE    EEE  EEE   ",
"  HEEEEEEH    HEEEEEEH    HEEEEEEH   ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"   EE  EE      EE  EE      EE  EE    ",
"  HEE  EEH    HEE  EEH    HEE  EEH   ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
" HEEE  EEEH  HEEE  EEEH  HEEE  EEEH  ",
"  EEEEEEEE    EEEEEEEE    EEEEEEEE   ",
"                                     ",
"                                     ",
"                                     ",
/* sou7_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"              EEEEEEEE               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              HEE  EEH               ",
"               EE  EE                ",
"               EE  EE                ",
"              HEEEEEEH               ",
"              EEE  EEE               ",
"              HEEEEEEH               ",
"               EE  EE                ",
"               EE  EE                ",
"              HEE  EEH               ",
"             HEEE  EEEH              ",
"             HEEE  EEEH              ",
"              EEEEEEEE               ",
"                                     ",
"                                     ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCC   ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
"  CCC  CCC    CCC  CCC    CCC  CCC   ",
"   CC  CC      CC  CC      CC  CC    ",
"   CC  CC      CC  CC      CC  CC    ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCC   ",
"  CCC  CCC    CCC  CCC    CCC  CCC   ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCC   ",
"   CC  CC      CC  CC      CC  CC    ",
"   CC  CC      CC  CC      CC  CC    ",
"  CCC  CCC    CCC  CCC    CCC  CCC   ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCCC  ",
"                                     ",
"                                     ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCC   ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
"  CCC  CCC    CCC  CCC    CCC  CCC   ",
"   CC  CC      CC  CC      CC  CC    ",
"   CC  CC      CC  CC      CC  CC    ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCC   ",
"  CCC  CCC    CCC  CCC    CCC  CCC   ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCC   ",
"   CC  CC      CC  CC      CC  CC    ",
"   CC  CC      CC  CC      CC  CC    ",
"  CCC  CCC    CCC  CCC    CCC  CCC   ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
" CCCC  CCCC  CCCC  CCCC  CCCC  CCCC  ",
"  CCCCCCCC    CCCCCCCC    CCCCCCCC   ",
"                                     ",
"                                     ",
/* sou8_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"  EEEEEEEE     HHHHHH     EEEEEEEE   ",
" HEEE  EEEH    EEEEEE    HEEE  EEEH  ",
" HEEE  EEEH   HEEEEEEH   HEEE  EEEH  ",
" HEEE  EEEH    EE  EE    HEEE  EEEH  ",
"  HEE  EEH    HEH  HEH    HEE  EEH   ",
"   EE  EE     EE    EE     EE  EE    ",
"   EE  EE    HEH EE HEH    EE  EE    ",
"   EE  EE    EE HEEH EE    EE  EE    ",
"   EE  EE   HEH EEEE HEH   EE  EE    ",
"  HEEEEEEH HEE HE  EH EEH HEEEEEEH   ",
"  EEE  EEE HEHEEE  EEEHEH EEE  EEE   ",
"  EEE  EEE EE HEH  HEH EE EEE  EEE   ",
"  HEEEEEEHHEHEEEE  EEEEHEHHEEEEEEH   ",
"   EE  EE EE HEEH  HEEH EE EE  EE    ",
"   EE  EEHEH EEH    HEE HEHEE  EE    ",
"   EE  EEEE HE        EH EEEE  EE    ",
"   EE  EEEH EH        HE HEEE  EE    ",
"  HEE  EEH HE          EH HEE  EEH   ",
" HEEE  EEEHEH          HEHEEE  EEEH  ",
" HEEE  EEEEE            EEEEE  EEEH  ",
" HEEE  EEEE              EEEE  EEEH  ",
"  EEEEEEEEE              EEEEEEEEE   ",
"                                     ",
"                                     ",
"                                     ",
"  EEEEEEEEE              EEEEEEEEE   ",
" HEEE  EEEE              EEEE  EEEH  ",
" HEEE  EEEEE            EEEEE  EEEH  ",
" HEEE  EEEHEH          HEHEEE  EEEH  ",
"  HEE  EEH HE          EH HEE  EEH   ",
"   EE  EEEH EH        HE HEEE  EE    ",
"   EE  EEEE HE        EH EEEE  EE    ",
"   EE  EEHEH EEH    HEE HEHEE  EE    ",
"   EE  EE EE HEEH  HEEH EE EE  EE    ",
"  HEEEEEEHHEHEEEE  EEEEHEHHEEEEEEH   ",
"  EEE  EEE EE HEH  HEH EE EEE  EEE   ",
"  EEE  EEE HEHEEE  EEEHEH EEE  EEE   ",
"  HEEEEEEH HEE HE  EH EEH HEEEEEEH   ",
"   EE  EE   HEH EEEE HEH   EE  EE    ",
"   EE  EE    EE HEEH EE    EE  EE    ",
"   EE  EE    HEH EE HEH    EE  EE    ",
"   EE  EE     EE    EE     EE  EE    ",
"  HEE  EEH    HEH  HEH    HEE  EEH   ",
" HEEE  EEEH    EE  EE    HEEE  EEEH  ",
" HEEE  EEEH   HEEEEEEH   HEEE  EEEH  ",
" HEEE  EEEH    EEEEEE    HEEE  EEEH  ",
"  EEEEEEEE     HHHHHH     EEEEEEEE   ",
"                                     ",
"                                     ",
"                                     ",
/* sou9_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"  EEEEEEEE    DDDDDDDD    EEEEEEEE   ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
"  CEE  EEC    CDD  DDC    CEE  EEC   ",
"   EE  EE      DD  DD      EE  EE    ",
"   EE  EE      DD  DD      EE  EE    ",
"  CEEEEEEC    CDDDDDDC    CEEEEEEC   ",
"  EEE  EEE    DDD  DDD    EEE  EEE   ",
"  CEEEEEEC    CDDDDDDC    CEEEEEEC   ",
"   EE  EE      DD  DD      EE  EE    ",
"   EE  EE      DD  DD      EE  EE    ",
"  CEE  EEC    CDD  DDC    CEE  EEC   ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
"  EEEEEEEE    DDDDDDDD    EEEEEEEE   ",
"                                     ",
"                                     ",
"  EEEEEEEE    DDDDDDDD    EEEEEEEE   ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
"  CEE  EEC    CDD  DDC    CEE  EEC   ",
"   EE  EE      DD  DD      EE  EE    ",
"   EE  EE      DD  DD      EE  EE    ",
"  CEEEEEEC    CDDDDDDC    CEEEEEEC   ",
"  EEE  EEE    DDD  DDD    EEE  EEE   ",
"  CEEEEEEC    CDDDDDDC    CEEEEEEC   ",
"   EE  EE      DD  DD      EE  EE    ",
"   EE  EE      DD  DD      EE  EE    ",
"  CEE  EEC    CDD  DDC    CEE  EEC   ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
"  EEEEEEEE    DDDDDDDD     EEEEEEE   ",
"                                     ",
"                                     ",
"  EEEEEEEE    DDDDDDDD    EEEEEEEE   ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
"  CEE  EEC    CDD  DDC    CEE  EEC   ",
"   EE  EE      DD  DD      EE  EE    ",
"   EE  EE      DD  DD      EE  EE    ",
"  CEEEEEEC    CDDDDDDC    CEEEEEEC   ",
"  EEE  EEE    DDD  DDD    EEE  EEE   ",
"  CEEEEEEC    CDDDDDDC    CEEEEEEC   ",
"   EE  EE      DD  DD      EE  EE    ",
"   EE  EE      DD  DD      EE  EE    ",
"  CEE  EEC    CDD  DDC    CEE  EEC   ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
" CEEE  EEEC  CDDD  DDDC  CEEE  EEEC  ",
"  EEEEEEEE    DDDDDDDD    EEEEEEEE   ",
"                                     ",
"                                     ",
/* ton_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"             AAAA                    ",
"             ABBBA                   ",
"              ABBBA                  ",
"              ABBBA                  ",
"               ABA  AA               ",
"               ABA ABAA              ",
"               ABA BBBBA             ",
"              AABBBBBAA              ",
"            ABBBBBBA                 ",
"         ABBBBBBBA   ABA             ",
"         AABAA ABAABBBBBB            ",
"             AAABBBAAABBBBA          ",
"        AAAAABBBBB    BBBBB          ",
"        BBBBAAAABA    BBBBA          ",
"         BBA   ABA AA BBBA           ",
"         ABB   ABAABBBBBB            ",
"          ABA ABBBBAABBBA            ",
"          ABABBBBBA  BBB             ",
"           AB  ABA  BBBA             ",
"           ABA ABAABBBBA             ",
"           ABAAABBBBBBB              ",
"            BBBBBBA  AA              ",
"            ABBBBAA                  ",
"             ABABABA                 ",
"            ABBABAABA                ",
"            BB ABA ABBA              ",
"           BBA ABA AABBAA            ",
"          ABA  ABA  AABBBAA          ",
"         ABA   ABA   AABBBBBAAAA     ",
"        ABA    ABA    AABBBBBBBAA    ",
"       ABAA    ABA     AABBBBAA      ",
"      BAA  A   ABA      ABBAA        ",
"    AA      AA ABA       AA          ",
"            ABAABA                   ",
"             ABBBA                   ",
"             ABBBA                   ",
"              ABBA                   ",
"              ABBA                   ",
"               BBA                   ",
"               ABA                   ",
"                AA                   ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* nan_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"              ABA                    ",
"              ABBB                   ",
"              AABBA                  ",
"               ABBB                  ",
"                BBA                  ",
"                BB                   ",
"                BB                   ",
"                BB   AA              ",
"                BB BBBBA             ",
"                BBBBBBBB             ",
"               ABBBAAAA              ",
"          AAABBBBB    ABA            ",
"          BBBBB BB   ABBA            ",
"           AA   BB   BBB AA          ",
"                BB  ABBBABBA         ",
"                BB  BBBBBBBBA        ",
"         ABA    BBABBBBBBBBBBA       ",
"          BB    BBBBBBBBBBBBBBA      ",
"     AA    BBBBBBBBABA   ABBBBB      ",
"     ABAA  ABBBA   BA    ABBBBBA     ",
"      BBA  BBBA    B     ABBBBBA     ",
"      BBB    BB    A      BBBBBA     ",
"      BBB     BA  B       BBBBB      ",
"      BBB      B  BBAA    BBBBB      ",
"      BBBA     BBBBBBB   ABBBBA      ",
"      ABBA  BBBBBB       ABBBB       ",
"      ABBA  ABB BB BBA   ABBBB       ",
"       BBA      BBBBBBA  ABBBA       ",
"       ABB    BBBBBAAA   ABBB        ",
"       ABBA ABBBBBA     ABBBB        ",
"        BBA ABBABB      ABBBA        ",
"        ABB     BB      ABBBA        ",
"         BBA    BB      ABBB         ",
"         ABA    BB      BBBA         ",
"         ABB  BBBB     ABBBA         ",
"          AA   ABB     ABBB          ",
"                AAB  AABBBA          ",
"                  ABBBBBBBA          ",
"                   ABBBBBA           ",
"                     ABBB            ",
"                      AAA            ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* sya_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                  AAAABBBBAAAAA      ",
"             AAABBBBBBBBBBBBBBBA     ",
"          AABBBBBBBBBBBBBBBBBBBBA    ",
"       AABBBAAAAA        BBBBBBBA    ",
"      AABAAA            ABBBBAAA     ",
"    AAAA               ABBBAA        ",
"                   A  ABBAA          ",
"             AAA   BBABAA            ",
"             ABB   BBA               ",
"             ABB   BB    BBAA        ",
"             ABB  ABBAABBBBBAA       ",
"              BB ABBBBBBBBBBBAA      ",
"              BB B BBBBBBBBBBBA      ",
"              ABBBBBBBBBBBBBBBBA     ",
"      A      ABBBBBBB    ABBBBBB     ",
"      BBA ABBBBBA  BB     BBBBBB     ",
"      ABBBBBA ABA  BB     BBBBBA     ",
"      ABBB    ABA  BB     BBBBAA     ",
"       BBBA   ABA  BB    ABBBBA      ",
"       ABBA   ABA  BA    ABBBB       ",
"        BBA    BA  BA    ABBBA       ",
"        ABB    BA  BA    BBBBA       ",
"         BBA   AB  B     BBBB        ",
"         ABA   AB  B     BBBA        ",
"          BB   AB  B    ABBBA        ",
"          AB   AB  B    BBBA         ",
"          ABA  AB AA   ABBBA         ",
"           BA  AB BA   ABBB          ",
"           ABA  B B    BBBA          ",
"           ABA  B B   BBBBA          ",
"           ABA  B BBBBBBBBA          ",
"            BBBBBBBBBBBBBA           ",
"            BBBBBBBBBBBBBA           ",
"            BBBBBBBBBBBBB            ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* pei_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                ABA                  ",
"                BBBBA                ",
"                 BBBBA               ",
"                 ABBBB               ",
"                 ABBBA               ",
"                  BBAA               ",
"                  BBA                ",
"                  BBA                ",
"          AAA     BB                 ",
"          ABBA    BB                 ",
"          ABBB    BB                 ",
"           BBBA   BB      BBA        ",
"           ABBA   BB      BBBA       ",
"           ABBA   BB     ABBBBA      ",
"     AA    ABB    BB     ABBBBA      ",
"     BBAA  ABB    BB     BBBBA       ",
"     ABBBA ABB    BB    ABBAA        ",
"      BBBB ABB    BB    BBA          ",
"      ABBA ABB    BB   ABA           ",
"       ABA ABB    BBA ABA            ",
"       AB  ABB    BBAAB              ",
"        B  ABB    BBBA               ",
"        A  ABB    BBA                ",
"        A  ABB    BBA                ",
"        A  ABB    BBA                ",
"       A   ABB    BBA                ",
"       B   BBB    BBA                ",
"      AA  BBBB    BBA                ",
"      BA BBBBB    BBA                ",
"     BA BBABBB    BBAA     AABAA     ",
"    ABBBBA  BB    ABBAAAAABBBBBBAA   ",
"   ABBBBA   AA    ABBBBBBBBBBBBBBA   ",
"  ABBBBA           ABBBBBBBBBBBBBA   ",
"  BBBBBA            AABBBBBBBBAAA    ",
"  ABBBA                              ",
"   ABA                               ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* haku_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* hatu_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                     H               ",
"                    HEH              ",
"               HH  HEEE              ",
"              HEE  HEEH              ",
"             HEEEH EEH               ",
"            EEEEEEEEH                ",
"           EEEEEEEEH                 ",
"            EHEE  EH   H             ",
"             HEH EEEH EE             ",
"       H    HEE H  EEEE              ",
"       EE   EEH    EEH               ",
"       EE   EH     EEH               ",
"       HEE HE     EEEEH              ",
"        EEEEE    EE HEE              ",
"          EEH   EHE HEEH             ",
"          EE    H EE HEEH            ",
"         HEH      EE  HEE            ",
"         EE       EE   EEH           ",
"        HEH EEH   EH   HEEH          ",
"        EE HEEE  HE HEEEHEEH         ",
"       HEH E EE  EEEEEEEHEEEH        ",
"      HEH    EE EEEEEEEH HEEEH       ",
"      EE  HHEE  H  EE    HEEEEEH     ",
"     HE  HEE       EE  H  HEEEEEEEH  ",
"    HE   EE        EEEEEH HEEEEEEH   ",
"   HE   HEHEH     HEEEEEE  EEHH      ",
"  HE    EEEEEH EEEEEE      HH        ",
"       HEEEHEE  EE EE                ",
"      EEE   EEE    EH                ",
"      HH    EEH   HEH HEEEH          ",
"           HEE    HE    EEEH         ",
"           EEH    EH    HEEEH        ",
"       H  HEE     EH     EEEE        ",
"       HEEEEH    EH      HEEH        ",
"        HEEE    EH        HH         ",
"         HEH   H                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* cyun_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"               CCC                   ",
"               DDDC                  ",
"               CDDDC                 ",
"                CDDC                 ",
"                CDDC                 ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC      DDC         ",
"                CDC    CDDDDC        ",
"                CDCCCDDDDDDDDC       ",
"              CCDDCDDDDDDDDDDDC      ",
"    CDDDCDDDCCCCCDC       DDDDDC     ",
"     DDDDDCC    CDC       DDDDDC     ",
"     CDDDC      CDC       DDDDDC     ",
"      DDDC      CDC      CDDDDC      ",
"      CDDDC     CDC      CDDDC       ",
"       DDDC     CDC      DDDDC       ",
"       CDDC     CDC     CDDDC        ",
"        CDD     CDCCCCDDDDDC         ",
"        CDDCCCDDDDCDDDDDDDDC         ",
"         DDDDDC DDC    CDDC          ",
"         DDCC   CDC     CC           ",
"         CC     CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                CDC                  ",
"                 D                   ",
"                 C                   ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ", 
/* man5r_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                    CCC              ",
"              C    CDDDD             ",
"           C   DDDDDDDDC             ",
"           DC   DCCCC                ",
"           DDC     DC                ",
"          CDD      D                 ",
"         CDD      DCDDC              ",
"         DD     CCDDDDDC             ",
"        DCD CCDDDDC  DDDC            ",
"       DC DC CDDCDC  DDC             ",
"      DC  DD  CC D  CDDC             ",
"          DC    DC  CDD              ",
"         CDC    D   DDC              ",
"        CDD DDDDDDDDDDDDDDDDDDDC     ",
"        DDC CDDDDCC     CDDDDDC      ",
"        CDC  CDC          CDCC       ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                 CD                  ",
"                DDD                  ",
"               C CDC                 ",
"             C    D                  ",
"            CD    D  CDC             ",
"             DD  CDCDDDDD            ",
"             CDDDDC                  ",
"        CDDDDDCC   CD                ",
"         CDDCC   CDDDC               ",
"              CDDD DDDC              ",
"          C DDDDD  DDDC              ",
"           D   DD CDDC               ",
"           CD CDDDDDDC               ",
"            D  DD  DD                ",
"            D  DDDDDC                ",
"            DDDDDD DC CCCC           ",
"            D  DD  CDDDDDDCC         ",
"               DDDDDCCC CDDDC        ",
"             CDDD  C     CDDDC       ",
"      CC   CDD DD  DDC    DDDDC      ",
"        DDC    DD  DDDD  CDDDD       ",
"        CDD    DDDD CDC  DDDDC       ",
"         DDCDDDDDC       DDDD        ",
"         DDCCDDDC  DDDDDDDDDC        ",
"         CC  CC      CDDDDDC         ",
"                       CDCA          ",
"                                     ",
"                                     ",
"                                     ",
/* pin5r_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"       CDDDC             CDDDC       ",
"     CDC   CDC         CDC   CDC     ",
"    CD  DDD  DC       CD  DDD  DC    ",
"    D CDC CDC D       D CDC CDC D    ",
"   CC D DDD D CC     CC D DDD D CC   ",
"   D D  D D  D D     D D  D D  D D   ",
"   D DCD D DCD D     D DCD D DCD D   ",
"   D DD D D DD D     D DD D D DD D   ",
"   CC D  D  D CC     CC D  D  D CC   ",
"    D CDCDCDC D       D CDCDCDC D    ",
"    CD  DDD  DC       CD  DDD  DC    ",
"     CDC   CDC         CDC   CDC     ",
"       CDDDC             CDDDC       ",
"                                     ",
"                                     ",
"                CDDDC                ",
"              CDC   CDC              ",
"             CD  DDD  DC             ",
"             D CDC CDC D             ",
"            CC D DDD D CC            ",
"            D D  D D  D D            ",
"            D DCD D DCD D            ",
"            D DD D D DD D            ",
"            CC D  D  D CC            ",
"             D CDCDCDC D             ",
"             CD  DDD  DC             ",
"              CDC   CDC              ",
"                CDDDC                ",
"                                     ",
"                                     ",
"       CDDDC             CDDDC       ",
"     CDC   CDC         CDC   CDC     ",
"    CD  DDD  DC       CD  DDD  DC    ",
"    D CDC CDC D       D CDC CDC D    ",
"   CC D DDD D CC     CC D DDD D CC   ",
"   D D  D D  D D     D D  D D  D D   ",
"   D DCD D DCD D     D DCD D DCD D   ",
"   D DD D D DD D     D DD D D DD D   ",
"   CC D  D  D CC     CC D  D  D CC   ",
"    D CDCDCDC D       D CDCDCDC D    ",
"    CD  DDD  DC       CD  DDD  DC    ",
"     CDC   CDC         CDC   CDC     ",
"       CDDDC             CDDDC       ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"                                     ",
/* sou5r_xpm[] */
"                                     ",
"                                     ",
"                                     ",
"                                     ",
"  DDDDDDDD                DDDDDDDD   ",
" CDDD  DDDC              CDDD  DDDC  ",
" CDDD  DDDC              CDDD  DDDC  ",
" CDDD  DDDC              CDDD  DDDC  ",
"  CDD  DDC                CDD  DDC   ",
"   DD  DD                  DD  DD    ",
"   DD  DD                  DD  DD    ",
"   DD  DD                  DD  DD    ",
"   DD  DD                  DD  DD    ",
"  CDDDDDDC                CDDDDDDC   ",
"  DDD  DDD                DDD  DDD   ",
"  DDD  DDD                DDD  DDD   ",
"  CDDDDDDC                CDDDDDDC   ",
"   DD  DD     DDDDDDDD     DD  DD    ",
"   DD  DD    CDDD  DDDC    DD  DD    ",
"   DD  DD    CDDD  DDDC    DD  DD    ",
"   DD  DD    CDDD  DDDC    DD  DD    ",
"  CDD  DDC    CDD  DDC    CDD  DDC   ",
" CDDD  DDDC    DD  DD    CDDD  DDDC  ",
" CDDD  DDDC    DD  DD    CDDD  DDDC  ",
" CDDD  DDDC    DD  DD    CDDD  DDDC  ",
"  DDDDDDDD     DD  DD     DDDDDDDD   ",
"              CDDDDDDC               ",
"              DDD  DDD               ",
"              DDD  DDD               ",
"  DDDDDDDD    CDDDDDDC    DDDDDDDD   ",
" CDDD  DDDC    DD  DD    CDDD  DDDC  ",
" CDDD  DDDC    DD  DD    CDDD  DDDC  ",
" CDDD  DDDC    DD  DD    CDDD  DDDC  ",
"  CDD  DDC     DD  DD     CDD  DDC   ",
"   DD  DD     CDD  DDC     DD  DD    ",
"   DD  DD    CDDD  DDDC    DD  DD    ",
"   DD  DD    CDDD  DDDC    DD  DD    ",
"   DD  DD    CDDD  DDDC    DD  DD    ",
"  CDDDDDDC    DDDDDDDD    CDDDDDDC   ",
"  DDD  DDD                DDD  DDD   ",
"  DDD  DDD                DDD  DDD   ",
"  CDDDDDDC                CDDDDDDC   ",
"   DD  DD                  DD  DD    ",
"   DD  DD                  DD  DD    ",
"   DD  DD                  DD  DD    ",
"   DD  DD                  DD  DD    ",
"  CDD  DDC                CDD  DDC   ",
" CDDD  DDDC              CDDD  DDDC  ",
" CDDD  DDDC              CDDD  DDDC  ",
" CDDD  DDDC              CDDD  DDDC  ",
"  DDDDDDDD                DDDDDDDD   ",
"                                     ",
"                                     ",
"                                     ",
};
