/* XPM */
static char * base_24c0_xpm[] = {
"32 32 13 1",
" 	c #000000000000",
".	c #FFFFBEFB79E7",
"X	c #BEFBBEFBBEFB",
"o	c #BEFB6DB64103",
"O	c #BEFB7DF74103",
"+	c #B6DAB2CAB6DA",
"@	c #EFBEEFBEEFBE",
"#	c #DF7DDB6CDF7D",
"$	c #FFFFFFFFFFFF",
"%	c #9E799E799E79",
"&	c #8E388E388E38",
"*	c #CF3CCF3CCF3C",
"=	c #CF3CCB2BCF3C",
" ............................XX ",
".ooooooooooooooooooooooooooooOO+",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+",
"o@############################O+",
"$@############################%+",
"$@#############################+",
"$@#############################+",
"$@#############################+",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#&",
"$$***************************++&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$*============================+&",
"$+============================+&",
"$&++++++++++++++++++++++++++++&&",
" &&&&&&&&&&&&&&&&&&&&&&&&&&&&&& "};
/* XPM */
static char * base_24c3_xpm[] = {
"26 38 12 1",
" 	c #000000000000",
".	c #FFFFBEFB79E7",
"X	c #BEFBBEFBBEFB",
"o	c #BEFB6DB64103",
"O	c #BEFB7DF74103",
"+	c #B6DAB2CAB6DA",
"@	c #EFBEEFBEEFBE",
"#	c #DF7DDB6CDF7D",
"$	c #FFFFFFFFFFFF",
"%	c #CF3CCF3CCF3C",
"&	c #8E388E388E38",
"*	c #CF3CCB2BCF3C",
" ......................XX ",
".ooooooooooooooooooooooOO+",
"OOOOOOOOOOOOOOOOOOOOOOOOO+",
"o@######################O+",
"$@######################++",
"$@######################++",
"$@######################++",
"$@######################++",
"$$$$$$$$$$$$$$$$$$$$$$$$++",
"$$%%%%%%%%%%%%%%%%%%%%%++&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$%**********************+&",
"$+**********************+&",
"$&++++++++++++++++++++++&&",
" &&&&&&&&&&&&&&&&&&&&&&&& "};
/* XPM */
static char * base_24o0_xpm[] = {
"32 32 13 1",
" 	c #000000000000",
".	c #FFFFFFFFFFFF",
"X	c #DF7DDB6CDF7D",
"o	c #B6DAB2CAB6DA",
"O	c #CF3CCF3CCF3C",
"+	c #8E388E388E38",
"@	c #DF7DDF7DDF7D",
"#	c #CF3CCB2BCF3C",
"$	c #9E799E799E79",
"%	c #BEFBBEFBBEFB",
"&	c #BEFB7DF74103",
"*	c #BEFB6DB64103",
"=	c #BEFB4D344103",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXoo ",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXXXXXXXo+",
"..@@@@@@@@@@@@@@@@@@@@@@@@@@@oo+",
"..............................o+",
".@############################$o",
".@############################$o",
".@############################$o",
".@############################$o",
"%@############################&o",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*",
"=****************************&&*",
" ============================== "};
/* XPM */
static char * base_24o3_xpm[] = {
"26 38 13 1",
" 	c #000000000000",
".	c #FFFFFFFFFFFF",
"X	c #DF7DDB6CDF7D",
"o	c #B6DAB2CAB6DA",
"O	c #CF3CCF3CCF3C",
"+	c #8E388E388E38",
"@	c #DF7DDF7DDF7D",
"#	c #CF3CCB2BCF3C",
"$	c #9E799E799E79",
"%	c #BEFBBEFBBEFB",
"&	c #BEFB7DF74103",
"*	c #BEFB6DB64103",
"=	c #BEFB4D344103",
" .XXXXXXXXXXXXXXXXXXXXXoo ",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
".OXXXXXXXXXXXXXXXXXXXXXXo+",
"..@@@@@@@@@@@@@@@@@@@@@oo+",
"........................o+",
".@######################$o",
".@######################$o",
".@######################$o",
".@######################$o",
"%@######################&o",
"&&&&&&&&&&&&&&&&&&&&&&&&&*",
"=**********************&&*",
" ======================== "};
/* XPM */
static char * rev_24c2_xpm[] = {
"19 24 9 1",
" 	c #CF3CCB2BCF3C",
".	c #FFFFFFFFFFFF",
"X	c #9E799E799E79",
"a	c #CF3CCF3CCF3C",
"O	c #000041030000",
"+	c #FFFF9A696185",
"@	c #BEFB6DB630C2",
"#	c #FFFFBAEA8617",
"o	c #DF7DDB6CDF7D",
"XXXXXXXXXXXXX+++++O",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
".ooooooooooooo@+++ ",
"O.............####+"};
/* XPM */
static char * rev_24c0_xpm[] = {
"19 24 9 1",
" 	c #CF3CCB2BCF3C",
".	c #FFFFFFFFFFFF",
"X	c #9E799E799E79",
"a	c #CF3CCF3CCF3C",
"O	c #000041030000",
"+	c #FFFF9A696185",
"@	c #BEFB6DB630C2",
"#	c #FFFFBAEA8617",
"o	c #DF7DDB6CDF7D",
"O++++XXXXXXXXXXXXXX",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
" +++@ooooooooooooo.",
"+####............ O"};
/* XPM */
static char * rev_24c3_xpm[] = {
"26 38 8 1",
" 	c #49244D3438E3",
".	c #CF3CCF3CCF3C",
"X	c #9E799E799E79",
"o	c #BEFB71C64924",
"O	c #FFFF9A696185",
"+	c #BEFB6DB630C2",
"@	c #FFFFBAEA8617",
"#	c #DF7D86175144",
" ......................XX ",
"........................X ",
"........................Xo",
"........................Xo",
"........................Xo",
"........................Xo",
".OOOOOOOOOOOOOOOOOOOOOOO+o",
".@OOOOOOOOOOOOOOOOOOOOOO+o",
".@@@@@@@@@@@@@@@@@@@@@@@+o",
".@OOOOOOOOOOOOOOOOOOOOO##o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".OOOOOOOOOOOOOOOOOOOOOOO#o",
".@OOOOOOOOOOOOOOOOOOOOO##o",
"oooooooooooooooooooooooooo"};
/* XPM */
static char * rev_24o0_xpm[] = {
"32 32 9 1",
" 	c #000041030000",
".	c #CF3CCF3CCF3C",
"X	c #9E799E799E79",
"o	c #E79DE38DE79D",
"O	c #FFFF9A696185",
"+	c #BEFB6DB630C2",
"@	c #FFFFBAEA8617",
"#	c #BEFB7DF74103",
"$	c #410382074103",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX  ",
"o.OOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o@OOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO# ",
"o.............................# ",
"o.............................# ",
"o.............................X ",
"o.............................X ",
"o.............................X ",
"$.............................X$"};
/* XPM */
static char * rev_24o3_xpm[] = {
"26 38 6 1",
" 	c #BEFB71C64924",
".	c #CF3CCF3CCF3C",
"X	c #9E799E799E79",
"o	c #FFFF9A696185",
"O	c #DF7D86175144",
"+	c #FFFFBAEA8617",
" .XXXXXXXXXXXXXXXXXXXXXX  ",
"..oooooooooooooooooooooOO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".oooooooooooooooooooooooO ",
".+oooooooooooooooooooooOO ",
".+++++++++++++++++++++++O ",
".+ooooooooooooooooooooooO ",
".ooooooooooooooooooooooo  ",
"........................X ",
"........................X ",
"........................X ",
"........................X ",
"........................X ",
" .......................X "};
/* XPM */
static char * base_24do0_xpm[] = {
"32 32 12 1",
" 	c #CF3CCF3CCF3C",
".	c #AEBAAEBAAEBA",
"X	c #965892489658",
"o	c #69A66DB669A6",
"O	c #AEBAAAAAAEBA",
"+	c #DF7DDF7DDF7D",
"@	c #9E799E799E79",
"#	c #BEFB6DB64103",
"$	c #BEFB7DF74103",
"%	c #BEFB4D344103",
"&	c #000065950000",
"*	c #000000000000",
"                                ",
" .............................Xo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOOOOOOOXo",
" +++++++++++++++++++++++++++++Xo",
"                              Xo",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
"#+OOOOOOOOOOOOOOOOOOOOOOOOOOOO$X",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X",
"%############################$$X",
"&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%*&"};
/* XPM */
static char * base_24do3_xpm[] = {
"26 38 12 1",
" 	c #CF3CCF3CCF3C",
".	c #AEBAAEBAAEBA",
"X	c #965892489658",
"o	c #69A66DB669A6",
"O	c #AEBAAAAAAEBA",
"+	c #DF7DDF7DDF7D",
"@	c #9E799E799E79",
"#	c #BEFB6DB64103",
"$	c #BEFB7DF74103",
"%	c #BEFB4D344103",
"&	c #000065950000",
"*	c #000000000000",
"                          ",
" .......................Xo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" .OOOOOOOOOOOOOOOOOOOOOOXo",
" +++++++++++++++++++++++Xo",
"                        Xo",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
"#+OOOOOOOOOOOOOOOOOOOOOO$X",
"$$$$$$$$$$$$$$$$$$$$$$$$$X",
"%######################$$X",
"&&%%%%%%%%%%%%%%%%%%%%%%*&"};
/* XPM */
static char * rev_24do0_xpm[] = {
"32 32 8 1",
" 	c #000030C20000",
".	c #9E799A699E79",
"X	c #71C675D671C6",
"o	c #BEFBBEFBBEFB",
"O	c #BEFB6DB671C6",
"+	c #8E385D7530C2",
"@	c #BEFB6DB64103",
"#	c #410382074103",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXX  ",
"o.OOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o@OOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o.............................+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o.............................+ ",
"o.............................+ ",
"o.............................X ",
"o.............................X ",
"o.............................X ",
"#.............................X#"};
/* XPM */
static char * rev_24do3_xpm[] = {
"26 38 8 1",
" 	c #000030C20000",
".	c #9E799A699E79",
"X	c #71C675D671C6",
"o	c #BEFBBEFBBEFB",
"O	c #BEFB6DB671C6",
"+	c #8E385D7530C2",
"@	c #BEFB6DB64103",
"#	c #410382074103",
" .XXXXXXXXXXXXXXXXXXXXXX  ",
"o.OOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o@OOOOOOOOOOOOOOOOOOOOOO+ ",
"o.......................+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o.......................+ ",
"o.......................+ ",
"o.......................X ",
"o.......................X ",
"o.......................X ",
"#.......................X#"};
/* XPM */
static char * base_24o0c_xpm[] = {
"32 9 13 1",
" 	c #000000000000",
".	c #FFFFFFFFFFFF",
"X	c #DF7DDB6CDF7D",
"o	c #B6DAB2CAB6DA",
"O	c #CF3CCF3CCF3C",
"+	c #8E388E388E38",
"@	c #DF7DDF7DDF7D",
"#	c #CF3CCB2BCF3C",
"$	c #9E799E799E79",
"%	c #BEFBBEFBBEFB",
"&	c #BEFB7DF74103",
"*	c #BEFB6DB64103",
"=	c #BEFB4D344103",
"..............................o+",
".@############################$o",
".@############################$o",
".@############################$o",
".@############################$o",
"%@############################&o",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*",
"=****************************&&*",
" ============================== "};
/* XPM */
static char * base_24o3c_xpm[] = {
"26 9 13 1",
" 	c #000000000000",
".	c #FFFFFFFFFFFF",
"X	c #DF7DDB6CDF7D",
"o	c #B6DAB2CAB6DA",
"O	c #CF3CCF3CCF3C",
"+	c #8E388E388E38",
"@	c #DF7DDF7DDF7D",
"#	c #CF3CCB2BCF3C",
"$	c #9E799E799E79",
"%	c #BEFBBEFBBEFB",
"&	c #BEFB7DF74103",
"*	c #BEFB6DB64103",
"=	c #BEFB4D344103",
"........................o+",
".@######################$o",
".@######################$o",
".@######################$o",
".@######################$o",
"%@######################&o",
"&&&&&&&&&&&&&&&&&&&&&&&&&*",
"=**********************&&*",
" ======================== "};
/* XPM */
static char * rev_24o0c_xpm[] = {
"32 9 9 1",
" 	c #000041030000",
".	c #CF3CCF3CCF3C",
"X	c #9E799E799E79",
"o	c #E79DE38DE79D",
"O	c #FFFF9A696185",
"+	c #BEFB6DB630C2",
"@	c #FFFFBAEA8617",
"#	c #BEFB7DF74103",
"$	c #410382074103",
"o@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO# ",
"o.............................# ",
"o.............................# ",
"o.............................X ",
"o.............................X ",
"o.............................X ",
"$.............................X$"};
/* XPM */
static char * rev_24c2c_xpm[] = {
"19 26 10 1",
" 	c #000041030000",
".	c #CF3CCF3CCF3C",
"X	c #9E799E799E79",
"o	c #4F4F4F4F4F4F",
"O	c #FFFF9A696185",
"+	c #BEFB6DB630C2",
"@	c #FFFFBAEA8617",
"#	c #BEFB7DF74103",
"$	c #410382074103",
"a	c #E3E39A696185",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X..............aaa#",
"X..............aaa#",
"X..............aaa#",
"X..............aaa#",
"X..............aaa#",
"X..............aaa#",
"X..............aaa#",
"X..............aaa#",
"X..............aaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"X.............aaaa#",
"$$$$$$$$$$$$$$$$$$$"};
/* XPM */
static char * rev_24c0c_xpm[] = {
"19 26 10 1",
" 	c #000041030000",
".	c #CF3CCF3CCF3C",
"X	c #9E799E799E79",
"o	c #4F4F4F4F4F4F",
"O	c #FFFF9A696185",
"+	c #BEFB6DB630C2",
"@	c #FFFFBAEA8617",
"#	c #BEFB7DF74103",
"$	c #410382074103",
"a	c #E3E39A696185",
"#aaaa.............+",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaa..............X",
"#aaa..............X",
"#aaa..............X",
"#aaa..............X",
"#aaa..............X",
"#aaa..............X",
"#aaa..............X",
"#aaa..............X",
"#aaa..............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"#aaaa.............X",
"$$$$$$$$$$$$$$$$$$$"};
/* XPM */
static char * rev_24o3c_xpm[] = {
"26 9 6 1",
" 	c #BEFB71C64924",
".	c #CF3CCF3CCF3C",
"X	c #9E799E799E79",
"o	c #FFFF9A696185",
"O	c #DF7D86175144",
"+	c #FFFFBAEA8617",
".+++++++++++++++++++++++O ",
".+ooooooooooooooooooooooO ",
".ooooooooooooooooooooooo  ",
"........................X ",
"........................X ",
"........................X ",
"........................X ",
"........................X ",
" .......................X "};
/* XPM */
static char * base_24do0c_xpm[] = {
"32 9 12 1",
" 	c #CF3CCF3CCF3C",
".	c #AEBAAEBAAEBA",
"X	c #965892489658",
"o	c #69A66DB669A6",
"O	c #AEBAAAAAAEBA",
"+	c #DF7DDF7DDF7D",
"@	c #9E799E799E79",
"#	c #BEFB6DB64103",
"$	c #BEFB7DF74103",
"%	c #BEFB4D344103",
"&	c #000065950000",
"*	c #000000000000",
"                              Xo",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOOOOOOOO@X",
"#+OOOOOOOOOOOOOOOOOOOOOOOOOOOO$X",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X",
"%############################$$X",
"&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%*&"};
/* XPM */
static char * base_24do3c_xpm[] = {
"26 9 12 1",
" 	c #CF3CCF3CCF3C",
".	c #AEBAAEBAAEBA",
"X	c #965892489658",
"o	c #69A66DB669A6",
"O	c #AEBAAAAAAEBA",
"+	c #DF7DDF7DDF7D",
"@	c #9E799E799E79",
"#	c #BEFB6DB64103",
"$	c #BEFB7DF74103",
"%	c #BEFB4D344103",
"&	c #000065950000",
"*	c #000000000000",
"                        Xo",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
" +OOOOOOOOOOOOOOOOOOOOOO@X",
"#+OOOOOOOOOOOOOOOOOOOOOO$X",
"$$$$$$$$$$$$$$$$$$$$$$$$$X",
"%######################$$X",
"&&%%%%%%%%%%%%%%%%%%%%%%*&"};
/* XPM */
static char * rev_24do0c_xpm[] = {
"32 9 8 1",
" 	c #000030C20000",
".	c #9E799A699E79",
"X	c #71C675D671C6",
"o	c #BEFBBEFBBEFB",
"O	c #BEFB6DB671C6",
"+	c #8E385D7530C2",
"@	c #BEFB6DB64103",
"#	c #410382074103",
"o.............................+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o.............................+ ",
"o.............................+ ",
"o.............................X ",
"o.............................X ",
"o.............................X ",
"#.............................X#"};
/* XPM */
static char * rev_24do3c_xpm[] = {
"26 9 8 1",
" 	c #000030C20000",
".	c #9E799A699E79",
"X	c #71C675D671C6",
"o	c #BEFBBEFBBEFB",
"O	c #BEFB6DB671C6",
"+	c #8E385D7530C2",
"@	c #BEFB6DB64103",
"#	c #410382074103",
"o.......................+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"oOOOOOOOOOOOOOOOOOOOOOOO+ ",
"o.......................+ ",
"o.......................+ ",
"o.......................X ",
"o.......................X ",
"o.......................X ",
"#.......................X#"};
/* XPM */
static char * base_24_xpm[] = {
"25 31 2 1",
" 	c #EFBEEFBEE79D",
".	c #000000000000",
".........................",
"..                     ..",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
".                       .",
"..                     ..",
"........................."};
/* XPM */
static char * base_24h_xpm[] = {
"31 25 2 1",
" 	c #EFBEEFBEE79D",
".	c #000000000000",
"...............................",
"..                           ..",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
".                             .",
"..                           ..",
"..............................."};
/* XPM */
static char * rev_24_xpm[] = {
"25 31 3 1",
" 	c #EFBEEFBEE79D",
".	c #000000000000",
"X	c #EFBE75D60000",
".........................",
"..XXXXXXXXXXXXXXXXXXXXX..",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
"..XXXXXXXXXXXXXXXXXXXXX..",
"........................."};
/* XPM */
static char * rev_24h_xpm[] = {
"31 25 3 1",
" 	c #EFBEEFBEE79D",
".	c #000000000000",
"X	c #EFBE75D60000",
"...............................",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXX..",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXX..",
"..............................."};
/* XPM */
static char * base_24d_xpm[] = {
"25 31 3 1",
" 	c #EFBEEFBEE79D",
".	c #000000000000",
"X      c #AEBAAAAAAEBA",
".........................",
"..XXXXXXXXXXXXXXXXXXXXX..",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXX.",
"..XXXXXXXXXXXXXXXXXXXXX..",
"........................."};
/* XPM */
static char * base_24dh_xpm[] = {
"31 25 3 1",
" 	c #EFBEEFBEE79D",
".	c #000000000000",
"X      c #AEBAAAAAAEBA",
"...............................",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXX..",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
".XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXX..",
"..............................."};
