static char * paicolor[] = {
"A      c DarkOrange2",
"B      c ForestGreen",
"C      c black",
"D      c tomato2"};

static char * paidata[] = {
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"          CCCCC      ",
"    CCCCCCC   CC     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"          CCCC       ",
"       CCCC          ",
"                     ",
"                     ",
"            CCC      ",
"         CCC   CC    ",
"    CCCCC            ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"          CCCCC      ",
"      CCCCC          ",
"                     ",
"          CCCC       ",
"       CCCC          ",
"                     ",
"          CCCCC      ",
"    CCCCCCC    CC    ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"         CCCCCCC     ",
"    CCCCCC C   CC    ",
"    C   C  C   CC    ",
"     C  C  C   C     ",
"     C  C  C  CC     ",
"      C   CCCCC      ",
"      CCCCC          ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"           CCCC      ",
"       CCCCC         ",
"       C   C         ",
"      CC   CCCC      ",
"      C CCCC  C      ",
"     CC   C  CC      ",
"     CC   C  C       ",
"    C CCCCCCCCCCCC   ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"         C           ",
"          CCCCCC     ",
"    CCCCCC     CC    ",
"                     ",
"       C    C        ",
"      C      C       ",
"      C      C       ",
"     C        C      ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"        C            ",
"        C   CCCCC    ",
"        CCCC         ",
"      CCC            ",
"    CC  C            ",
"        C            ",
"        CC  CCC      ",
"         CCCC        ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"        CCC          ",
"           C         ",
"           C         ",
"       C    C        ",
"     CC     C        ",
"    C        CCCC    ",
"                     ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"        C            ",
"        CCCCCC       ",
"    CCCCC  C         ",
"       C   C         ",
"       C  CC    C    ",
"       C  C     C    ",
"     CC   C     C    ",
"    C     CCCCCC     ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"        CCCCC        ",
"      CC     CC      ",
"     C  DDDDD  C     ",
"    C  D     D  C    ",
"    C D  CCC  D C    ",
"   C D  C   C  D C   ",
"   C D C     C D C   ",
"   C D C     C D C   ",
"   C D C     C D C   ",
"   C D  C   C  D C   ",
"    C D  CCC  D C    ",
"    C  D     D  C    ",
"     C  DDDDD  C     ",
"      CC     CC      ",
"        CCCCC        ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"        CCCCC        ",
"       C     C       ",
"      C  CCC  C      ",
"     C  C   C  C     ",
"     C C     C C     ",
"     C C     C C     ",
"     C C     C C     ",
"     C  C   C  C     ",
"      C  CCC  C      ",
"       C     C       ",
"        CCCCC        ",
"                     ",
"        CCCCC        ",
"       C     C       ",
"      C  CCC  C      ",
"     C  C   C  C     ",
"     C C     C C     ",
"     C C     C C     ",
"     C C     C C     ",
"     C  C   C  C     ",
"      C  CCC  C      ",
"       C     C       ",
"        CCCCC        ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"   CCC               ",
"  C   C              ",
" C CCC C             ",
" C C C C             ",
" C CCC C             ",
"  C   C              ",
"   CCC               ",
"                     ",
"         CCC         ",
"        C   C        ",
"       C DDD C       ",
"       C D D C       ",
"       C DDD C       ",
"        C   C        ",
"         CCC         ",
"                     ",
"              CCC    ",
"             C   C   ",
"            C CCC C  ",
"            C C C C  ",
"            C CCC C  ",
"             C   C   ",
"              CCC    ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"    CCC       CCC    ",
"   C   C     C   C   ",
"  C CCC C   C CCC C  ",
"  C C C C   C C C C  ",
"  C CCC C   C CCC C  ",
"   C   C     C   C   ",
"    CCC       CCC    ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"    CCC       CCC    ",
"   C   C     C   C   ",
"  C CCC C   C CCC C  ",
"  C C C C   C C C C  ",
"  C CCC C   C CCC C  ",
"   C   C     C   C   ",
"    CCC       CCC    ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"    CCC       CCC    ",
"   C   C     C   C   ",
"  C CCC C   C CCC C  ",
"  C C C C   C C C C  ",
"  C CCC C   C CCC C  ",
"   C   C     C   C   ",
"    CCC       CCC    ",
"         CCC         ",
"        C   C        ",
"       C DDD C       ",
"       C D D C       ",
"       C DDD C       ",
"        C   C        ",
"         CCC         ",
"    CCC       CCC    ",
"   C   C     C   C   ",
"  C CCC C   C CCC C  ",
"  C C C C   C C C C  ",
"  C CCC C   C CCC C  ",
"   C   C     C   C   ",
"    CCC       CCC    ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"    CCC       CCC    ",
"   C   C     C   C   ",
"  C CCC C   C CCC C  ",
"  C C C C   C C C C  ",
"  C CCC C   C CCC C  ",
"   C   C     C   C   ",
"    CCC       CCC    ",
"                     ",
"                     ",
"                     ",
"    DDD       DDD    ",
"   D   D     D   D   ",
"  D DDD D   D DDD D  ",
"  D D D D   D D D D  ",
"  D DDD D   D DDD D  ",
"   D   D     D   D   ",
"    DDD       DDD    ",
"   D   D     D   D   ",
"  D DDD D   D DDD D  ",
"  D D D D   D D D D  ",
"  D DDD D   D DDD D  ",
"   D   D     D   D   ",
"    DDD       DDD    ",
"                     ",
"                     ",
"                     ",
"                     ",
"   CCC               ",
"  C   C              ",
" C CCC C             ",
" C C C C CCC         ",
" C CCC CC   C        ",
"  C   CC CCC C CCC   ",
"   CCC C C C CC   C  ",
"       C CCC C CCC C ",
"        C   CC C C C ",
"         CCC C CCC C ",
"              C   C  ",
"               CCC   ",
"     DDD     DDD     ",
"    D   D   D   D    ",
"   D DDD D D DDD D   ",
"   D D D D D D D D   ",
"   D DDD D D DDD D   ",
"    D   D   D   D    ",
"     DDD     DDD     ",
"     DDD     DDD     ",
"    D   D   D   D    ",
"   D DDD D D DDD D   ",
"   D D D D D D D D   ",
"   D DDD D D DDD D   ",
"    D   D   D   D    ",
"     DDD     DDD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"      CC    CC       ",
"     C   C C   C     ",
"    C     C     C    ",
"    C  CC C  CC C    ",
"    C  CC C  CC C    ",
"     C   C C   C     ",
"      CCC   CCC      ",
"     C   C C   C     ",
"    C     C     C    ",
"    C  CC C  CC C    ",
"    C  CC C  CC C    ",
"     C   C C   C     ",
"      CCC   CCC      ",
"     C   C C   C     ",
"    C     C     C    ",
"    C  CC C  CC C    ",
"    C  CC C  CC C    ",
"     C   C C   C     ",
"      CCC   CCC      ",
"     C   C C   C     ",
"    C     C     C    ",
"    C  CC C  CC C    ",
"    C  CC C  CC C    ",
"     C   C C   C     ",
"      CCC   CCC      ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"   CCC   CCC   CCC   ",
"  C   C C   C C   C  ",
" C     C     C     C ",
" C  CC C  CC C  CC C ",
" C  CC C  CC C  CC C ",
"  C   C C   C C   C  ",
"   CCC   CCC   CCC   ",
"                     ",
"   CCC   CCC   CCC   ",
"  C   C C   C C   C  ",
" C     C     C     C ",
" C  DD C  DD C  DD C ",
" C  DD C  DD C  DD C ",
"  C   C C   C C   C  ",
"   CCC   CCC   CCC   ",
"                     ",
"   CCC   CCC   CCC   ",
"  C   C C   C C   C  ",
" C     C     C     C ",
" C  CC C  CC C  CC C ",
" C  CC C  CC C  CC C ",
"  C   C C   C C   C  ",
"   CCC   CCC   CCC   ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"            B D B    ",
"            B D B    ",
"            B D B    ",
"            B D B    ",
"            B D B    ",
"            B D B    ",
"        BBBBB D B    ",
"      BB    BBD B    ",
"     BB     B DBB    ",
"     B         B     ",
"    B           B    ",
"    B           B    ",
"    B           B    ",
"    B  BB       B    ",
"    B  B        B    ",
"     BBB       B     ",
"     BB       BB     ",
"     BBB B   BB      ",
"     B BBBBBB        ",
"    BBBB             ",
"    BB               ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"        BBBBB        ",
"         B B         ",
"         B B         ",
"         B B         ",
"         B B         ",
"        BBBBB        ",
"         B B         ",
"         B B         ",
"         B B         ",
"         B B         ",
"        BBBBB        ",
"                     ",
"                     ",
"        BBBBB        ",
"         B B         ",
"         B B         ",
"         B B         ",
"         B B         ",
"        BBBBB        ",
"         B B         ",
"         B B         ",
"         B B         ",
"         B B         ",
"        BBBBB        ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"        BBBBB        ",
"         B B         ",
"         B B         ",
"         B B         ",
"         B B         ",
"        BBBBB        ",
"         B B         ",
"         B B         ",
"         B B         ",
"         B B         ",
"        BBBBB        ",
"                     ",
"                     ",
"   BBBBB     BBBBB   ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"   BBBBB     BBBBB   ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"   BBBBB     BBBBB   ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"   BBBBB     BBBBB   ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"   BBBBB     BBBBB   ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"   BBBBB     BBBBB   ",
"                     ",
"   BBBBB     BBBBB   ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"   BBBBB     BBBBB   ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"    B B       B B    ",
"   BBBBB     BBBBB   ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"  BBBBB       BBBBB  ",
"   B B         B B   ",
"   B B         B B   ",
"   B B         B B   ",
"   B B         B B   ",
"  BBBBB       BBBBB  ",
"   B B         B B   ",
"   B B  DDDDD  B B   ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"  BBBBB  D D  BBBBB  ",
"         D D         ",
"        DDDDD        ",
"         D D         ",
"  BBBBB  D D  BBBBB  ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"   B B  DDDDD  B B   ",
"   B B         B B   ",
"  BBBBB       BBBBB  ",
"   B B         B B   ",
"   B B         B B   ",
"   B B         B B   ",
"   B B         B B   ",
"  BBBBB       BBBBB  ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"                     ",
"                     ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"                     ",
"                     ",
"                     ",
"                     ",
"        DDDDD        ",
"         D D         ",
"         D D         ",
"        DDDDD        ",
"         D D         ",
"         D D         ",
"        DDDDD        ",
"                     ",
"                     ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"                     ",
"                     ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"   B B   B B   B B   ",
"   B B   B B   B B   ",
"  BBBBB BBBBB BBBBB  ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
" BBBBB         BBBBB ",
"  B B     B     B B  ",
"  B B    B B    B B  ",
"  B B   B   B   B B  ",
" BBBBB B  B  B BBBBB ",
"  B B B  B B  B B B  ",
"  B BB  B   B  BB B  ",
"  B B  B     B  B B  ",
" BBBBBB       BBBBBB ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
" BBBBBB       BBBBBB ",
"  B B  B     B  B B  ",
"  B BB  B   B  BB B  ",
"  B B B  B B  B B B  ",
" BBBBB B  B  B BBBBB ",
"  B B   B   B   B B  ",
"  B B    B B    B B  ",
"  B B     B     B B  ",
" BBBBB         BBBBB ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"  BBBBB DDDDD BBBBB  ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"  BBBBB DDDDD BBBBB  ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"  BBBBB DDDDD BBBBB  ",
"                     ",
"                     ",
"  BBBBB DDDDD BBBBB  ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"  BBBBB DDDDD BBBBB  ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"  BBBBB DDDDD BBBBB  ",
"                     ",
"                     ",
"  BBBBB DDDDD BBBBB  ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"  BBBBB DDDDD BBBBB  ",
"   B B   D D   B B   ",
"   B B   D D   B B   ",
"  BBBBB DDDDD BBBBB  ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"          C          ",
"          C          ",
"          C CC       ",
"         CCC         ",
"       CC C          ",
"          CCCC       ",
"       CCCC   C      ",
"    CCC   C    C     ",
"     C    CCCCCC     ",
"     CCCCCC   C      ",
"      C   C  CC      ",
"      C   CCCC       ",
"       CCCC          ",
"        C CC         ",
"       C  CCC        ",
"      C   C CC       ",
"    CC C  C  C       ",
"  CC    C C   CC     ",
"         CC    CCC   ",
"         CC      CC  ",
"          C          ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"          C          ",
"          C          ",
"          C          ",
"          C CC       ",
"         CCC         ",
"       CC C   C      ",
"          C  CCC     ",
"       C  CCCC  C    ",
"       C CC CC   C   ",
"    C CCC   C     C  ",
"    CC  C  C      C  ",
"    C   C CCCC    C  ",
"    C  CCCC      C   ",
"    CC    C      C   ",
"     C    CCCC   C   ",
"     C CCCC      C   ",
"     C    C     C    ",
"     C    C  CC C    ",
"               CC    ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"           CCCCCCC   ",
"    CCCCCCC  CCC     ",
"           CC        ",
"          C          ",
"       CCC  C        ",
"   C   C   C CCC     ",
"   C   CCCCCC   C    ",
"    CCCC   C     C   ",
"    C  C   C    CC   ",
"    C  CC  C    C    ",
"     C  C  C   CC    ",
"     C  C  C   C     ",
"     C  C  C  CC     ",
"      C C CCCCC      ",
"      CCCCCC         ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"           C         ",
"       C   C         ",
"       C   C    C    ",
"       C   C  CC     ",
"  CCC  C   C CC      ",
"    CCCC   CCC       ",
"       C   C         ",
"    C  C C C         ",
"    C  CC  C         ",
"   C  CC   C         ",
"   C CCC   C         ",
"   CCC     C         ",
"  CC       CC   CCC  ",
"  C         CCCC     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"             B       ",
"             B       ",
"        BBB B        ",
"      BBBBB B        ",
"   B    BB B         ",
"   BB  BB  B   B     ",
"    B  B    B B      ",
"      B      B       ",
"     B    B BB       ",
"    B  BB B   B      ",
"   B BBB B     B     ",
"  B   B  BBBBBBB     ",
"     BBBB  B    B    ",
"       BB  B     B   ",
"     BBBBBBBBBB   B  ",
"  BBBB B   B         ",
"       B  B  B       ",
"    B BB B    BB     ",
"     BB B       B    ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"          D          ",
"          D          ",
"          D          ",
"          D          ",
"          D          ",
"          D  DDDD    ",
"   D   DDDDDD   DD   ",
"    DDD   D     D    ",
"    D     D     D    ",
"     D    D    D     ",
"      D   D   D      ",
"      D   D   D      ",
"       DDDDDDD       ",
"          D          ",
"          D          ",
"          D          ",
"          D          ",
"          D          ",
"          D          ",
"          D          ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"           DDDD      ",
"       DDDDD         ",
"       D   D         ",
"      DD   DDDD      ",
"      D DDDD  D      ",
"     DD   D  DD      ",
"     DD   D  D       ",
"    D DDDDDDDDDDDD   ",
"                     ",
"                     ",
"       D    D        ",
"       D    D        ",
"        D DDDD       ",
"      DDDD D         ",
"          DDD        ",
"       DDDD D        ",
"       DDDDDD        ",
"       D  DDD DDD    ",
"       DDDDDDDD DD   ",
"    D DDDDD      D   ",
"    DDD  D DD    D   ",
"     D   DD D   D    ",
"     D DDD  D   D    ",
"             DDD     ",
"              DD     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"    DDD       DDD    ",
"   D   D     D   D   ",
"  D DDD D   D DDD D  ",
"  D D D D   D D D D  ",
"  D DDD D   D DDD D  ",
"   D   D     D   D   ",
"    DDD       DDD    ",
"         DDD         ",
"        D   D        ",
"       D DDD D       ",
"       D D D D       ",
"       D DDD D       ",
"        D   D        ",
"         DDD         ",
"    DDD       DDD    ",
"   D   D     D   D   ",
"  D DDD D   D DDD D  ",
"  D D D D   D D D D  ",
"  D DDD D   D DDD D  ",
"   D   D     D   D   ",
"    DDD       DDD    ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"                     ",
"  DDDDD       DDDDD  ",
"   D D         D D   ",
"   D D         D D   ",
"   D D         D D   ",
"   D D         D D   ",
"  DDDDD       DDDDD  ",
"   D D  DDDDD  D D   ",
"   D D   D D   D D   ",
"   D D   D D   D D   ",
"   D D   D D   D D   ",
"  DDDDD  D D  DDDDD  ",
"        DDDDD        ",
"         D D         ",
"  DDDDD  D D  DDDDD  ",
"   D D   D D   D D   ",
"   D D   D D   D D   ",
"   D D  DDDDD  D D   ",
"   D D         D D   ",
"  DDDDD       DDDDD  ",
"   D D         D D   ",
"   D D         D D   ",
"   D D         D D   ",
"   D D         D D   ",
"  DDDDD       DDDDD  ",
"                     ",
"                     "};
