/*  NETMAJ-XUI -- X User Interface --  Copyright Notice
 *
 *      Copyright (c) 1995,1996 Todo Software All rights reserved.
 *
 *   You can redistribute it and/or modify this software under the terms
 *  of the GNU General Public License version 2 as published by
 *  the Free Software Foundation.
 *
 *   This software is provided 'as-is', without any express or implied
 *  warranty.  In no event will the author be held liable for any damages
 *  arising from the use of this software.
 *
 *   Todo Software : NBC02365@niftyserve.or.jp
 */
/*  -*- Mode: C -*- 
 * This file is part of my project
 * 
 * config.h -- 
 * 
 * Author          : NBC02365@niftyserve.or.jp
 * Created On      : Tue May  9 00:50:01 1995
 * Last Modified By: NBC02365@niftyserve.or.jp
 * Last Modified On: Mon May 15 22:22:57 1995
 * 
 *  Copyright (C) 1995,1996 Todo Software All rights reserved
 */

/* autoconf.h is generated by configure automatically */
#include "autoconf.h"
#if 0
/* manual configuration definitions */
#define MSDOS 1
#define TURBOC 1
#endif

#define POSIX 1
